"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a%3gipx6qk83=&@nq!_g%vgid@4!sa8u!z$rdmn^pe-0wn3u*4'

# SECURITY WARNING: don't run with debug turned on in production!
# Set to False in production for security
DEBUG = True

# In production, set this to your domain(s)
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app.apps.RelationshipAppConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # CSP middleware for Content Security Policy (Task 2)
    'bookshelf.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Authentication settings
LOGIN_REDIRECT_URL = 'list_books'
LOGOUT_REDIRECT_URL = 'login'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
# Point Django to use our custom user model instead of the default User model
AUTH_USER_MODEL = 'bookshelf.CustomUser'

# ============================================================================
# SECURITY SETTINGS (Task 2 & Task 3)
# ============================================================================

# SECURE BROWSER XSS FILTER (Task 2)
# Enables browser's XSS filtering to help prevent cross-site scripting attacks
SECURE_BROWSER_XSS_FILTER = True

# X-FRAME-OPTIONS (Task 2 & Task 3)
# Prevents your site from being framed, protecting against clickjacking attacks
# Options: 'DENY', 'SAMEORIGIN', or None
X_FRAME_OPTIONS = 'DENY'

# SECURE CONTENT TYPE NOSNIFF (Task 2 & Task 3)
# Prevents browsers from MIME-sniffing a response away from the declared content-type
# This helps prevent XSS attacks that rely on MIME type confusion
SECURE_CONTENT_TYPE_NOSNIFF = True

# CSRF COOKIE SECURE (Task 2 & Task 3)
# Ensures CSRF cookies are only sent over HTTPS connections
# Set to True in production when using HTTPS
# Note: Set to False during development if not using HTTPS
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS

# SESSION COOKIE SECURE (Task 2 & Task 3)
# Ensures session cookies are only transmitted over HTTPS connections
# Set to True in production when using HTTPS
# Note: Set to False during development if not using HTTPS
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS



# HTTPS AND SECURE REDIRECTS (Task 3)
# Redirect HTTP to HTTPS (enable only in production)
SECURE_SSL_REDIRECT = False  # Set to True in production with HTTPS

# HTTP Strict Transport Security (HSTS)
SECURE_HSTS_SECONDS = 0  # Set to 31536000 in production
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False

# Proxy SSL Header (REQUIRED by secure header checks)
# Ensures Django recognizes HTTPS when behind a reverse proxy or load balancer
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')






# Content Security Policy (CSP) (Task 2)
# Note: This is a basic implementation. For production, consider using django-csp
# or configuring more granular policies
# CSP is set via middleware or response headers
# Example CSP header (can be set in middleware or via django-csp):
# Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'

